services:
  backend:
    build:
      context: services/backend
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./services/backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    ports:
      - "3001:3001"

  frontend:
    build:
      context: services/frontend
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./services/frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    
  db:
    image: postgres:15.10
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5433:5432
    volumes:
      - ./data:/data

volumes:
  backend_node_modules:
  frontend_node_modules:
